### ISSUE TITLE
Add data-grid to fips-assessments tasks

### ISSUE THREAD

**Issue by madorn** [opdev/fips-assessments#18]
Add Ansible tasks that can perform the following checks: https://github.com/opdev/fips-assessments/blob/main/data-grid/check.txt

opcap-ansible integration will be treated on https://github.com/opdev/opcap-ansible/issues/24

**Comment by madorn** [comment]
@jianrongzhang89 Hello Jianrong, can you confirm which Custom Resources you would like created for testing data-grid on fips-enabled ROSA?

Looking at https://github.com/opdev/fips-assessments/blob/main/data-grid/check.txt, what is the difference between 1 and 2?

**Comment by jianrongzhang89** [comment]
> @jianrongzhang89 Hello Jianrong, can you confirm which Custom Resources you would like created for testing data-grid on fips-enabled ROSA?
> 
> Looking at https://github.com/opdev/fips-assessments/blob/main/data-grid/check.txt, what is the difference between 1 and 2?
@madorn for #1, the service type of the infinispan is "datagrid" while #2 the service type is "cache". So they are for different CR configurations.

**Comment by madorn** [comment]
@jianrongzhang89 if `#2` is cache, just want to confirm that status will be `status condition type: Ready, status: True`. We do not see `status condition type: WellFormed, status: True` for `kind: Cache`.

**Comment by jianrongzhang89** [comment]
@madorn could you double check? Here is my sample CR, which has the status condition "WellFormed".
[example-infinispan.cr.txt](https://github.com/opdev/fips-assessments/files/12283201/example-infinispan.cr.txt)

**Comment by jianrongzhang89** [comment]
@madorn The kind should be Infinispan indeed. The difference between #1 and #2 is that spec.service.type is Cache vs DataGrid.

**Comment by madorn** [comment]
@jianrongzhang89 Our assumption is that because we are generating two kind:InfiniSpan (one with type Datagrid and other with type: Cache), that you also want to to create/verify a backup for each Infinispan instance as well as a Batch for each instance, is this true?
