### ISSUE TITLE
3Scale Operator tasks attempt to install CRD that isn't part of 3Scale

### ISSUE THREAD

**Issue by madorn** [opdev/fips-assessments#48]
[3Scale Operator Ansible tasks/checks](https://github.com/opdev/fips-assessments/tree/main/3scale-operator) attempts to install `APICast` CRD which is not part of the `3scale-operator` bundle. It appears that this CRD is from `apicast-operator`.

**Comment by madorn** [comment]
Upon reviewing [3scale-operator checks](https://github.com/opdev/fips-assessments/tree/main/3scale-operator), it appears that this particular check requires both the 3scale and apicast operator.

It also contains several setups steps for ROSA.

@yuriolisa did you install both operators when testing your solution? Also wondering if you performed these [steps](https://github.com/opdev/fips-assessments/blob/main/3scale-operator/setup.txt) when testing?

**Comment by yuriolisa** [comment]
@madorn, I tested only the APIManager steps, so I got confused; my first thought was that APICast would be already installed as an additional package for APIManager Operator on ROSA and the environment variables related to the S3 bucket's secret.
So, should I remove the APICast steps from the 3Scale fips-assessments?

**Comment by madorn** [comment]
@yuriolisa will test on Rosa cluster with [provided setup steps](https://github.com/opdev/fips-assessments/blob/main/3scale-operator/setup.txt) and get back to you .

**Comment by madorn** [comment]
@yuriolisa I've been testing on Rosa with FIPS enabled.

A note that the current 3scale tasks residing on the `main` do not run.

* `wait` and `wait_condition` need to be part of `kubernetes.core.k8s`.
*  You may need to increase `retries` and `delay` due to the amount of time for everything to be fully deployed and `ApiManager` to reach `Available: True`.
* We should add a task that creates the `3scaleportal` secret. Without the secret APIcast CR's won't deploy their associated  objects. Something like this in Ansible form: `oc create secret generic 3scaleportal --from-literal=AdminPortalURL=https://access-token@3scale-admin.3scale.apps.ocp413mdrosa.7gx5.p1.openshiftapps.com`
*  The `APIcast` objects do not appear to have status conditions. To verify ApiCast objects we want to ensure the resource is defined and that the associated ApiCast's deployment has conditions in available or ready state. We should ensure those checks are reflected there.
