### ISSUE TITLE
Determine workflow for publishing fips-assessment collection to private automation hub

### ISSUE THREAD

**Issue by madorn** [opdev/fips-assessments#61]
Our plan is to automate the testing/publishing of fips-assessment collections to private automation hub (PAH) upon any changes to this upstream repo.

We can also add newly approved collections to our execution environment image for ease of use when executing reports.

Right now, our team cluster's PAH is currently configured with SSO. As a result, PAH api tokens only live for 1-day. This token is needed to publish or install a collection to/from PAH via `ansible-galaxy` cli tool.

We will find a way to use a long-lived token so we can automate this process with no intervention.

A note that we will also need to update the primary playbooks to import `opdev.fips_assessments`.

**Comment by madorn** [comment]
We can adjust expiration of PAH API token by setting `GALAXY_TOKEN_EXPIRATION` in Automation Hub's worker `settings.py`. This can be updatd via `kind: AutomationHub` CR. The value is in minutes.

`oc -n aap patch automationhubs.automationhub.ansible.com/opdev-hub --type merge -p '{"spec": {"pulp_settings": {"GALAXY_TOKEN_EXPIRATION": 5256000}}}'`

`oc -n aap scale deploy/opdev-hub-worker --replicas=0`

`oc -n aap scale deploy/opdev-hub-worker --replicas=2`

**Comment by madorn** [comment]
@bcrochet configured our private automation hub for GitHub SSO. Not sure if @brochet's SSO account has ability to configure permission on collection repositories. 

Setting these permissions should allow for non-admin SSO users to push collection to PAH.

@itroyano and I dug around on PAH for a bit, trying to figure out how to login to PAH via local admin so we could create a group to give permissions on collection repositories.

**Comment by bcrochet** [comment]
My account, and @mrhillsman has that ability. There is an opdev group that I will assign perms to.

**Comment by itroyano** [comment]
Is there an option to create a "robot account" and assign it explicit "push collection" permissions, similarly to how Quay does for images?
I was thinking about a GH Action that uses something like https://github.com/ansible-cloud/aap_controller_action, or just straight-up shell Galaxy CLI, to trigger on a push to main.
