### ISSUE TITLE
Can't download published fips-assessment collection from private automation hub

### ISSUE THREAD

**Issue by madorn** [opdev/fips-assessments#74]
We are not able to download the published fips-assessment collection from our private automation hub.

Attempting to download the collection tarball via UI results in hang with no response.

Attempting to download via `ansible-galaxy collection install` results in following:

```
Starting collection install process
Fetching a collection tarball for 'opdev.fips_assessments:0.0.1+b437632' from Ansible Galaxy
Downloading https://opdev-hub-aap.apps.eng.opdev.io/api/galaxy/v3/plugin/ansible/content/published/collections/artifacts/opdev-fips_assessments-0.0.1+b437632.tar.gz to /Users/<username>/.ansible/tmp/ansible-local-701613ze3ms4z/tmp1wydh9xg/opdev-fips_assessments-0.0.1+b437632-o755pn83
ERROR! Failed to download collection tar from 'published' due to the following unforeseen error: <urlopen error [Errno 8] nodename nor servname provided, or not known>. <urlopen error [Errno 8] nodename nor servname provided, or not known>
```

Troubleshooting via `curl -v -L -u <username>:<password> https://opdev-hub-aap.apps.eng.opdev.io/api/galaxy/v3/plugin/ansible/content/published/colle[…]artifacts/opdev-fips_assessments-0.0.1+b437632.tar.gz` reveals multiple redirects that end up in `Could not resolve host: aap-hub-hl.aap.svc.cluster.local`

The fix may be to update `PULP_ANSIBLE_CONTENT_HOSTNAME` in `/etc/pulp/settings.py` with resolvable url. We should be able to do this via `kind: AutomationHub` spec.

**Comment by bcrochet** [comment]
Fixed the S3/minio URL in the storage secret to be the externally facing route.
